services:

  postgres:
    image: postgres:16
    container_name: employee-postgres
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  employee-app:
    image: employee-management-app:1.0
    container_name: employee-management-app
    ports:
      - "8095:8095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_db
      SPRING_DATASOURCE_USERNAME: employee_user
      SPRING_DATASOURCE_PASSWORD: employee_password
    depends_on:
      - postgres

volumes:
  postgres_data:
